service: mahjong-ai-tgbot

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
  timeout: 25
  memorySize: 1024

package:
  include:
    - ./TGLanguage
    - ./Tile
    - ./Player
    - ./Game
    - ./ScoringRules
    - ./MoveGenerator
    - ./MLUtils
    - ./TGBotServer
    - run_lambda.py
    - resources

  exclude:
    - resources/models/**
    - env/**
    - "*.pyc"
    - node_modules/**

functions:
  webhook:
    handler: run_lambda.webhook
    events:
      - http: POST /

  set_webhook:
    handler: run_lambda.set_webhook
    events:
      - http: POST /set_webhook
      
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    zip: true
    dockerizePip: true